version: '3'

services:
  nginx:
    build:
      context: ./nginx
    links:
      - php
    ports:
      - "80:4649"
    container_name: nginx
    networks:
      - local_net

  php:
    build:
      context: ./php
      args:
        - environment=local
    domainname: localhost
    volumes:
      - ../src/vtn-connect:/var/www/slim
      - ../src/vendor:/var/www/vendor
    container_name: php
    networks:
      - local_net

networks:
  local_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24